### ISSUE TITLE
这个方案感觉在开发阶段的局限性比较大

### ISSUE THREAD

**Issue by CommanderXL** [kenberkeley/universal-i18n-solution#1]
在开发阶段当中，因为不是运行时进行编译的，所以写的一些标定符，及其他语言环境及其对应的样式都无法在开发环境当中及时预览，所以在开发阶段也有一些不便之处

**Comment by kenberkeley** [comment]
无论是 Webpack / Gulp / Grunt 都可以在每次 Ctrl + S 的时候直接吐出编译后的静态资源文件，监听这些文件的变动以进行国际化，随后触发浏览器刷新。这在直接提供 locales 文件的情况下效率尤为高效。

**Comment by z525466324** [comment]
请求
