### ISSUE TITLE
多国家语言的疑问。

### ISSUE THREAD

**Issue by rrrrui** [kenberkeley/universal-i18n-solution#7]
我司是做海外项目的，每次多语言要13个国家还要多，如果都这样搞的话，感觉手都要抽筋了...  
多语言是一个很繁琐的事情，要校对文案，要修改文案。
我司是根据浏览器http请求的地区码来映射一个国家码，然后来请求对应的语言文件，正如你所说，这样独立出文件缺少上下文，维护起来比较难受。
我司流程  文案在线文档编辑，校验 --> 前端自动化生产对应的语言脚本-->根据语言码映射不同的语言文件。
感觉这个办法比较笨但是很灵活，不依赖框架，配合自动化转化语言脚本，效率也还算比较高。
 希望找到更高效的办法解决多语言问题

**Comment by kenberkeley** [comment]
如果技术栈统一的话，解决方案还是很成熟的，例如 React / Vue
