### ISSUE TITLE
无法处理多级目录下的html文件 

### ISSUE THREAD

**Issue by view868** [kenberkeley/universal-i18n-solution#8]
gulp.task('i18n', ['html'], function () {
    return gulp.src(['./dist/__build__/**/*.html'])
        .on('end', function () {
            // 多语言
            i18n({
                srcDir: path.join(__dirname, 'src'),
                buildDir: path.join(__dirname, 'dist/__build__'),
                distDir: path.join(__dirname, 'dist'),
                sourceLang: 'zh-cn',
                defaultLang: 'en',
                saveLocalesTo: path.join(__dirname, 'dist/locales.json')
            });
        });
});
用示例里面的js也无法处理多层目录下的html文件

**Comment by kenberkeley** [comment]
看看这样子可不可以：`**/*/*.html`

**Comment by view868** [comment]
**/*/*.html 也不行 不知道上次哪位仁兄怎么成功 - -！

**Comment by kenberkeley** [comment]
你还是 Google 一下 glob 的写法吧

**Comment by view868** [comment]
用i18n.js 有办法解决吗？

**Comment by kenberkeley** [comment]
关键源码在此 https://github.com/OneWayTech/i18n-static/blob/master/lib/index.js#L38

**Comment by view868** [comment]
解决了 感谢大佬 原来上一位仁兄是改了源码的- -！
